name: ROS2 Practice Check

on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up ROS2
      run: |
        sudo apt update && sudo apt install -y curl gnupg2 lsb-release
        sudo curl -sSL http://repo.ros2.org/repos.key | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main jammy main" > /etc/apt/sources.list.d/ros2-latest.list'
        sudo apt update && sudo apt install -y ros-humble-desktop

    - name: Source ROS2
      run: source /opt/ros/humble/setup.bash

    - name: Check Submissions
      run: |
        for dir in submissions/*; do
          if [ -d "$dir" ]; then
            for subdir in "$dir"/*; do
              if [ -d "$subdir" ]; then
                if [ ! -f "$subdir/package.xml" ]; then
                  echo "    Subdirectory $subdir is missing required files."
                  exit 1
                fi
              fi
            done
          fi
        done
